name: nomo_pagegrid
description: "A customizable Flutter widget for creating grid layouts with drag-and-drop functionality, page-based navigation, and smooth displacement animations."
version: 0.1.0
repository: https://github.com/nomo-app/nomo_pagegrid
issue_tracker: https://github.com/nomo-app/nomo_pagegrid/issues

topics:
  - grid
  - drag-drop
  - navigation
  - layout
  - widget

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.5"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

